### ISSUE TITLE
Pacbio analysis gets stuck "forever" at close to 100%

### ISSUE THREAD

**Issue by jzook** [svviz/svviz#35] opened 2015-12-14 22:08 UTC
I've had an issue with an event when running in batch mode, where it gets stuck at close to 100% for >1 hour and still hasn't finished.  Any ideas?

Here's the command line:
svviz -t batch --max-deletion-size 30000 --max-reads 30000 --skip-cigar --summary /Volumes/UHTS1/AJPacBio/PracticeSVs_vcfForsvviz_svvizsummary_pacbio_b.tsv --export /Volumes/UHTS1/AJPacBio/PracticeSVs_vcfForsvviz_svvizfigs -b /Volumes/UHTS1/AJPacBio/HG003/CSHL_bwamem_bam_GRCh37/BWA-MEM_HG003_merged_11_12.sort.bam -b /Volumes/UHTS1/AJPacBio/HG004/CSHL_bwamem_bam_GRCh37/BWA-MEM_HG004_merged_11_12.sort.bam -b /Volumes/UHTS1/AJPacBio/HG002/CSHL_bwamem_bam_GRCh37/BWA-MEM_HG002_merged_11_12.sort.bam --aln-quality 0.2 /Volumes/SSD960/references/human_g1k_v37.fasta /Volumes/UHTS1/AJPacBio/PracticeSVs_vcfForsvviz_test.vcf

Here's the event:
16  7733013 7733013 .   TGTATATATACACACACACACACATATATACGTATATATATGTGTGTGTGTATATATACACACACACATATATACGTATATATGTGTGTGTGTGTATATATATATATATATATATA    .   .   SVTYPE=INS

Here's where it gets stuck,and just keeps repeating the same line forever:
- BWA-MEM_HG003_m:ref total 98.7% [========== ] left:0.9s 0:100% 1:89% 2:100%     BWA-MEM_HG003_m:ref total 98.7% [========== ] left:0.9s 0:100% 1:89% 2:100%   + BWA-MEM_HG003_m:ref total 98.7% [========== ] left:0.9s 0:100% 1:89% 2:100%     BWA-MEM_HG003_m:ref total 98.7% [========== ] left:0.9s 0:100% 1:89% 2:100%   + BWA-MEM_HG003_m:ref total 98.7% [========== ] left:0.9s 0:100% 1:89% 2:100%     BWA-MEM_HG003_m:ref total 98.7% [========== ] left:0.9s 0:100% 1:89% 2:100%   + BWA-MEM_HG003_m:ref total 98.7% [========== ] left:0.9s 0:100% 1:89% 2:100%     BWA-MEM_HG003_m:ref total 98.7% [========== ] left:0.9s 0:100% 1:89% 2:100%   + BWA-MEM_HG003_m:ref total 98.7% [========== ] left:0.9s 0:100% 1:89% 2:100%     BWA-MEM_HG003_m:ref total 98.7% [========== ] left:0.9s 0:100% 1:89% 2:100%   + BWA-

**Comment by nspies** [comment] 2015-12-14 22:21
This is likely caused by this issue: https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library/issues/22. I've looked into workarounds but unfortunately it's not simple. Forgot about this, as very few people are using svviz on pacbio (that I know of). You can try emailing mengyao as she had suggested she was hoping to work on this at some point.

**Comment by jzook** [comment] 2015-12-14 22:39
Is there any possibility of just skipping an SV if it runs more than a
certain amount of time?  It looks like this is happening again - in 2 out
of the first 6 SVs I ran in batch mode.  If it's this common, it will make
running a lot of SVs really tedious.

**Comment by nspies** [comment] 2015-12-14 22:49
Gah, sorry it’s having so much trouble

Unfortunately, this causes python to crash — it’s running in multiprocessing mode, so one of the sub-processes actually died (at least, assuming you’re hitting this bug and not some other issue). I wasn’t able to figure out how to detect a subprocess that’s died from python. If we were able to do that, it’s possible that switching which sequence is getting aligned against which would be a workaround for the problem (ie which one is reference and which one is query). No way to know beforehand which should be which, though.

And I haven’t found another python-compatible smith-waterman alignment implementation that’s within 2 orders of magnitude of the speed with the ssw library. Otherwise I’d be happy to switch to something better maintained.

The bwa smith-waterman alignment implementation should be fast, but I don’t have the know-how to wrap it in python (this was I believe why ssw was published).

On Dec 14, 2015, at 2:39 PM, jzook <notifications@github.com<mailto:notifications@github.com>> wrote:

Is there any possibility of just skipping an SV if it runs more than a
certain amount of time? It looks like this is happening again - in 2 out
of the first 6 SVs I ran in batch mode. If it's this common, it will make
running a lot of SVs really tedious.

**Comment by jzook** [comment] 2015-12-14 22:55
That is unfortunate - I'll email the author also.  Would the problem be
alleviated if I ran in single-threaded mode?  Since I have a lot of events
to run, I could just run a bunch of batch processes at the same time in
single-threaded mode, and it probably would be just as efficient.

**Comment by nspies** [comment] 2015-12-14 23:00
I think this would at least make it crash, rather than running forever

On Dec 14, 2015, at 2:55 PM, jzook <notifications@github.com<mailto:notifications@github.com>> wrote:

That is unfortunate - I'll email the author also. Would the problem be
alleviated if I ran in single-threaded mode? Since I have a lot of events
to run, I could just run a bunch of batch processes at the same time in
single-threaded mode, and it probably would be just as efficient.

**Comment by nspies** [comment] 2016-01-29 02:55
I've implemented a workaround which uses subprocesses to wrap the ssw Smith-Waterman alignment library, allowing realignment to skip reads which crash ssw. To use this mode, specify `--processes -1`. See a1732c5beafd84e47a523fcb4eb42cb5f9509a34

**Comment by nspies** [comment] 2016-01-29 02:56
Note that this mode is several fold slower (depending on the length of the reads)

**Comment by nspies** [comment] 2016-02-04 23:55
closed by 756655b3af4d346235663a8f52a72ca2740e51dc

**Closed as completed by nspies** 2016-02-04 23:55 UTC
Labels: bug
